version: "3.8"

services:
  ytdownloader:
    image: ytdownloader:latest
    build: .
    container_name: ytdownloader
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Madrid
